name: Triage GitHub Issue

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to triage'
        required: true
        type: number

jobs:
  triage:
    name: 🔍 Triage
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      id-token: write
    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: ⚙️ Install skill
        # Do not install locally, as opencode will see a dirty local branch and raise a PR for the changes
        # See https://github.com/anomalyco/opencode/issues/21636
        run: bash ./install.sh --skill triaging-gh-issue

      - name: ✨ Run OpenCode
        uses: anomalyco/opencode/github@2b92c5677e830e95d34fc3d5664a69297d2d0b51 # v1.15.4
        env:
          OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: opencode-go/qwen3.6-plus
          prompt: |
            Use the triaging-gh-issue skill to triage issue ${{ github.event.issue.number || inputs.issue_number }}.
